export const INSPIRATIONAL_QUOTES = [
    { author: "Sun Tzu", quote: "A suprema arte da guerra é derrotar o inimigo sem lutar.", source: "A Arte da Guerra" },
    { author: "Miyamoto Musashi", quote: "Não faça nada que seja inútil.", source: "O Livro dos Cinco Anéis" },
    { author: "Marco Aurélio", quote: "Você tem poder sobre sua mente - não sobre eventos externos. Perceba isso, e você encontrará a força.", source: "Meditações" },
    { author: "Sêneca", quote: "As dificuldades fortalecem a mente, assim como o trabalho o faz com o corpo.", source: "Cartas a Lucílio" },
    { author: "Mark Manson", quote: "Quem você é, é definido por aquilo pelo qual você está disposto a lutar.", source: "A Sutil Arte de Ligar o F*da-se" },
    { author: "Epicteto", quote: "Primeiro diga a si mesmo o que você seria; e então faça o que você tem que fazer.", source: "Enchiridion" },
    { author: "Sun Tzu", quote: "No meio do caos, há também oportunidade.", source: "A Arte da Guerra" },
    { author: "Miyamoto Musashi", quote: "Perceba aquilo que não pode ser visto a olho nu.", source: "O Livro dos Cinco Anéis" },
    { author: "Marco Aurélio", quote: "A melhor vingança é ser diferente daquele que cometeu a injustiça.", source: "Meditações" },
    { author: "Sêneca", quote: "Sorte é o que acontece quando a preparação encontra a oportunidade.", source: "Cartas a Lucílio" },
    { author: "Ryan Holiday", quote: "O obstáculo no caminho se torna o caminho. Nunca se esqueça, em cada obstáculo há uma oportunidade de melhorar nossa condição.", source: "O Obstáculo é o Caminho" },
    { author: "Naval Ravikant", quote: "Desejo é um contrato que você faz consigo mesmo para ser infeliz até conseguir o que quer.", source: "O Almanaque de Naval Ravikant" },
    { author: "Friedrich Nietzsche", quote: "Aquele que tem um porquê para viver pode suportar quase qualquer como.", source: "Assim Falou Zaratustra" },
    { author: "Viktor Frankl", quote: "Quando não podemos mais mudar uma situação, somos desafiados a mudar a nós mesmos.", source: "Em Busca de Sentido" },
    { author: "Carl Jung", quote: "Eu não sou o que me aconteceu, eu sou o que escolho me tornar.", source: "Escritos Diversos" },
    { author: "Jordan Peterson", quote: "Compare a si mesmo com quem você foi ontem, não com quem outra pessoa é hoje.", source: "12 Regras para a Vida" },
    { author: "James Clear", quote: "Você não se eleva ao nível de suas metas. Você cai ao nível de seus sistemas.", source: "Hábitos Atômicos" },
    { author: "David Goggins", quote: "A única pessoa que pode te dizer que você não pode fazer algo é você mesmo. E você não precisa ouvir.", source: "Can't Hurt Me" },
    { author: "Lao Tzu", quote: "A jornada de mil milhas começa com um único passo.", source: "Tao Te Ching" },
    { author: "Aristóteles", quote: "Nós somos o que repetidamente fazemos. A excelência, então, não é um ato, mas um hábito.", source: "Ética a Nicômaco" },
    { author: "Confúcio", quote: "Não importa o quão devagar você vá, desde que você não pare.", source: "Os Analectos" },
    { author: "Platão", quote: "A primeira e melhor vitória é a conquista de si mesmo.", source: "Leis" },
    { author: "Heráclito", quote: "Nenhum homem jamais pisa no mesmo rio duas vezes, pois não é o mesmo rio e ele não é o mesmo homem.", source: "Fragmentos" },
    { author: "Maquiavel", quote: "É melhor ser temido do que amado, se você não pode ser ambos.", source: "O Príncipe" },
    { author: "George Orwell", quote: "Em tempos de engano universal, dizer a verdade é um ato revolucionário.", source: "1984" },
    { author: "Aldous Huxley", quote: "A realidade não é o que nos acontece, mas o que fazemos com o que nos acontece.", source: "Admirável Mundo Novo" },
    { author: "Sêneca", quote: "Não é o homem que tem pouco, mas o que anseia por mais, que é pobre.", source: "Cartas a Lucílio" },
    { author: "Epicteto", quote: "Não são os eventos que nos perturbam, mas nossos julgamentos sobre eles.", source: "Enchiridion" },
    { author: "Marco Aurélio", quote: "A felicidade da sua vida depende da qualidade dos seus pensamentos.", source: "Meditações" },
    { author: "Sun Tzu", quote: "Conheça o seu inimigo e conheça a si mesmo e você não temerá o resultado de cem batalhas.", source: "A Arte da Guerra" },
    { author: "Miyamoto Musashi", quote: "O caminho do guerreiro é a aceitação resoluta da morte.", source: "O Livro dos Cinco Anéis" },
    { author: "Mark Manson", quote: "A chave para uma boa vida não é se importar com mais; é se importar com menos, se importar apenas com o que é verdadeiro, imediato e importante.", source: "A Sutil Arte de Ligar o F*da-se" },
    { author: "Ryan Holiday", quote: "O ego é o inimigo.", source: "O Ego é Seu Inimigo" },
    { author: "James Clear", quote: "Cada ação que você toma é um voto para o tipo de pessoa que você deseja se tornar.", source: "Hábitos Atômicos" },
    { author: "Jordan Peterson", quote: "Arrume o seu quarto.", source: "12 Regras para a Vida" },
    { author: "Napoleão Bonaparte", quote: "A coragem não é ter a força para continuar; é continuar quando você não tem força.", source: "Correspondência" },
    { author: "Júlio César", quote: "Vim, vi, venci.", source: "Relatório ao Senado Romano" },
    { author: "Winston Churchill", quote: "Se você está atravessando o inferno, continue andando.", source: "Discursos" },
    { author: "Theodore Roosevelt", quote: "Não é o crítico que conta; (...) o crédito pertence ao homem que está de fato na arena.", source: "Cidadania em uma República" },
    { author: "Elon Musk", quote: "A persistência é muito importante. Você não deve desistir, a menos que seja forçado a desistir.", source: "Entrevista" },
    { author: "Bruce Lee", quote: "Não reze por uma vida fácil, reze pela força para suportar uma difícil.", source: "Artista da Vida" },
    { author: "Muhammad Ali", quote: "Eu odiava cada minuto de treinamento, mas eu dizia: 'Não desista. Sofra agora e viva o resto da sua vida como um campeão.'", source: "Entrevista" },
    { author: "Vince Lombardi", quote: "A perfeição não é alcançável, mas se buscarmos a perfeição, podemos alcançar a excelência.", source: "Discursos" },
    { author: "Kobe Bryant", quote: "A coisa mais importante é tentar e inspirar as pessoas para que elas possam ser ótimas no que quer que queiram fazer.", source: "Entrevista" },
    { author: "Arnold Schwarzenegger", quote: "A força não vem da vitória. Suas lutas desenvolvem suas forças. Quando você passa por dificuldades e decide não se render, isso é força.", source: "Total Recall" },
    { author: "Henry Ford", quote: "Se você pensa que pode ou se pensa que não pode, de qualquer forma você está certo.", source: "Autobiografia" },
    { author: "Steve Jobs", quote: "Seu tempo é limitado, então não o desperdice vivendo a vida de outra pessoa.", source: "Discurso de Stanford" },
    { author: "Bill Gates", quote: "É ótimo celebrar o sucesso, mas é mais importante prestar atenção às lições do fracasso.", source: "Entrevista" },
    { author: "Jeff Bezos", quote: "Sabia que, se eu falhasse, não me arrependeria, mas sabia que a única coisa de que poderia me arrepender era não tentar.", source: "Entrevista" },
    { author: "Warren Buffett", quote: "A regra nº 1 é nunca perder dinheiro. A regra nº 2 é nunca esquecer a regra nº 1.", source: "Cartas aos Acionistas" },
    { author: "Dalai Lama", quote: "O propósito de nossas vidas é ser feliz.", source: "A Arte da Felicidade" },
    { author: "Martin Luther King Jr.", quote: "A medida final de um homem não é onde ele se posiciona em momentos de conforto e conveniência, mas onde ele se posiciona em tempos de desafio e controvérsia.", source: "Força para Amar" },
    { author: "Nelson Mandela", quote: "Aprendi que a coragem não era a ausência de medo, mas o triunfo sobre ele.", source: "Longo Caminho para a Liberdade" },
    { author: "Albert Einstein", quote: "Uma pessoa que nunca cometeu um erro nunca tentou nada novo.", source: "Escritos" },
    { author: "Isaac Newton", quote: "Se eu vi mais longe, foi por estar sobre ombros de gigantes.", source: "Carta a Robert Hooke" },
    { author: "Galileu Galilei", quote: "E ainda assim, se move.", source: "Atribuído" },
    { author: "Charles Darwin", quote: "Não é o mais forte que sobrevive, nem o mais inteligente, mas o que melhor se adapta às mudanças.", source: "Origem das Espécies (interpretação)" },
    { author: "Sócrates", quote: "Uma vida não examinada não vale a pena ser vivida.", source: "Apologia de Sócrates (Platão)" },
    { author: "Descartes", quote: "Penso, logo existo.", source: "Discurso do Método" },
    { author: "Kant", quote: "Ouse saber! Tenha coragem de usar sua própria razão!", source: "O que é Esclarecimento?" },
    { author: "Shakespeare", quote: "Ser ou não ser, eis a questão.", source: "Hamlet" },
    { author: "Dostoievski", quote: "O homem é um mistério. É preciso desvendá-lo, e se passares a vida inteira a desvendá-lo, não digas que perdeste tempo.", source: "O Idiota" },
    { author: "Tolstói", quote: "Todos pensam em mudar o mundo, mas ninguém pensa em mudar a si mesmo.", source: "Guerra e Paz" },
    { author: "George S. Patton", quote: "Um bom plano, executado violentamente agora, é melhor do que um plano perfeito na próxima semana.", source: "Guerra como a Conheci" },
    { author: "Dwight D. Eisenhower", quote: "Os planos são inúteis, mas o planejamento é indispensável.", source: "Discursos" },
    { author: "Alexandre, o Grande", quote: "Não tenho medo de um exército de leões liderado por uma ovelha; tenho medo de um exército de ovelhas liderado por um leão.", source: "Atribuído" },
    { author: "Leonidas de Esparta", quote: "Venham pegá-las.", source: "Resposta a Xerxes (Plutarco)" },
    { author: "Jocko Willink", quote: "Disciplina é igual a liberdade.", source: "Disciplina é Liberdade" }
];
